import crypt
print("        //      //                                        				  ")
print("       //      //                                         				  ")
print("      //      //                                          				  ")
print("     //======//       _____                                                                ")
print("    //      // //|  //     \    //   //                                                    ")
print("   //      // // |  ||_____    //===//                                                     ")
print("  //      // //==|         \  //   //                                                      ")
print(" //      // //   |   \____// //   //                                                       ")
print("_____________________________________                                                      ")
print("------By: Ansh Vaid----v1.0----------                                                      ")
print("\n\n")
salta=crypt.mksalt(crypt.METHOD_CRYPT)
saltb=crypt.mksalt(crypt.METHOD_MD5)
saltc=crypt.mksalt(crypt.METHOD_BLOWFISH)
saltd=crypt.mksalt(crypt.METHOD_SHA256)
salte=crypt.mksalt(crypt.METHOD_SHA512)
print("CRYPT salt is: " + salta)
print("MD5 salt is: " + saltb)
print("BLOWFISH salt is: " + saltc)
print("SHA256 salt is: " + saltd)
print("SHA512 salt is: " + salte)
########################################################
print("---------------------------------------------------------------------------------------------")
hasha=crypt.crypt("rockyou",salta)
hashb=crypt.crypt("rockyou",saltb)
hashc=crypt.crypt("rockyou",saltc)
hashd=crypt.crypt("rockyou",saltd)
hashe=crypt.crypt("rockyou",salte)
print("CRYPT hash with salt is: " +  hasha)
print("MD5 hash with salt is: " +  hashb)
print("BLOWFISH hash with salt is: " +  hashc)
print("SHA256 hash with salt is: " +  hashd)
print("SHA512hash with salt is: " +  hashe)

